### PR TITLE
Include variable to define what files to autosave and hide errors with mksession

### PR DESCRIPTION
**Pull request by jordisantamaria**
The plugin is giving soo many errors all time, so I think It would be nice to let user decide what files want to autosave, to avoid those errors. Also mksession is giving error sometimes, for example in q: mode, so include silent to avoid show those errors, they are so annoying.

### CODE REVIEW

**Review by thaerkh — CHANGES_REQUESTED** [review]
Thanks for the contribution! I think the whitelist is fine and we can merge that, though separately from the Git repo constraint which we can put in a separate PR as a feature flag.

Forcing Git as a dependency isn't ideal in all scenarios, but if we add an option to auto-setup sessions for root-dir git repos then I think that would be a great feature.

**Comment by jordisantamaria** [comment]
I see, thanks for feedback, my bad to request PR with master branch, I included git feature later lol. I will update It to give a flag for git repository then.

**Comment by jordisantamaria** [comment]
@thaerkh I updated It to include variable g:workspace_only_git_dir to activate workspace only for git repositorys. Is it ok like this?

**Comment by thaerkh** [comment]
This looks good to me, thank you!

**Pull request merged**
